version = 1

[provenance]
signer_workflow = "meigma/template-k8s/.github/workflows/release.yml"

[[packages]]
name = "template-k8s"
description = "Meigma Kubernetes operator repository template starter."
tag_pattern = "v${version}"

[[packages.assets]]
os = "darwin"
arch = "amd64"
pattern = "template-k8s_${version}_darwin_amd64"

[[packages.assets]]
os = "darwin"
arch = "arm64"
pattern = "template-k8s_${version}_darwin_arm64"

[[packages.assets]]
os = "linux"
arch = "amd64"
pattern = "template-k8s_${version}_linux_amd64"

[[packages.assets]]
os = "linux"
arch = "arm64"
pattern = "template-k8s_${version}_linux_arm64"

[[packages.binaries]]
path = "template-k8s"
