---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - example.meigma.io
  resources:
  - nginxdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.meigma.io
  resources:
  - nginxdeployments/status
  verbs:
  - patch
